### ISSUE TITLE
MySQL Tables cannot be created because TextField objects do not define max_length

### ISSUE THREAD

**Issue by shsdev** [jnphilipp/django_oai_pmh#3]
Using Django 5.0.6 and mysqlclient 2.1.0 there is an error when trying to create the tables (`python manage.py migrate `):

```
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'prefix' used in key specification without a key length")
```

This might be because there is no max_length defined for the TextField objects:

```
models.TextField(verbose_name=" dc:relation"), null=True)
```

Possibly max_length should be added:

```
models.TextField(max_length=65535, verbose_name=" dc:relation"), null=True)
```

where 65535 bytes is the maximum size of a MySQL `TEXT` field.

**Comment by jnphilipp** [comment]
At the moment MySQL is not supported as the ArrayFields use is a PostgreSQL specific field.
